---
- name: "Add ppa Repository"
  become: yes
  apt_repository: repo=ppa:chris-lea/redis-server

- name: "Update apt"
  become: yes
  apt: update_cache=yes

# Install Redis server
- name: "Install Redis server"
  become: yes
  action: apt pkg=redis-server state=installed

# Ensure Redis server is running
- name: "Ensure Redis server is running"
  become: yes
  action: service name=redis-server state=started
