---
- name: "Add ppa Repository"
  become: yes
  apt_repository: repo=ppa:chris-lea/redis-server

- name: apt update
  apt: update_cache=yes cache_valid_time=3600
  register: apt_result
  until: apt_result|success
  retries: 3
  delay: 1
  sudo: yes
  ignore_errors: yes

- name: retry if needed using command apt-get update
  command: apt-get update
  sudo: yes
  when: apt_result|failed

# Install Redis server
- name: Install Redis
  become: yes
  apt: pkg=redis-server state=present

- name: Configure Redis
  template: src=redis.conf.j2 dest=/etc/redis/redis.conf
  notify:
    - Restart Redis
